language: cpp

sudo: false

compiler:
 - clang-3.7
 - gcc-4.9
 - gcc-5
        
addons:
 apt:
  packages:
    - time    
    - clang-3.7
    - gcc-4.9
    - gcc-5
    - cmake
    - ninja-build
    - libboost-dev 
    - libdevil-dev
    - libarchive-dev    
    
script:
 - "time bash build_release.sh"
