language: cpp

compiler:
        - clang
        - gcc

before_script:
        - "sudo apt-get update"
        - "sudo apt-get install libboost-all-dev libarchive-dev ninja-build libdevil-dev"

script:
        - "time bash build_release.sh"
