language: cpp

sudo: false

compiler:
 - clang
 - gcc
 
addons:
  apt_sources:
    - ubuntu-toolchain-r-test
    - george-edison55/cmake-3.x
  apt_packages:
    - time
    - cmake
    - g++-4.9
    - g++-5
    - ninja-build
    - libeigen3-dev
    - libboost-test-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-serialization-dev
    - libboost-program-options-dev
    - libdevil-dev
    - libarchive-dev     
    
script:
 - "bash build_release.sh --build-sys make"
