language: cpp

sudo: false

compiler:
 - clang
 - gcc
 
addons:
  apt_packages:
    - time
    - cmake
    - gcc-4.9
    - ninja-build
    - libeigen3-dev
    - libboost-test-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-serialization-dev
    - libboost-program-options-dev
    - libdevil-dev
    - libarchive-dev     
    
script:
 - "bash build_release.sh --build-sys make"
