language: cpp

sudo: false

compiler:
 - clang
 - gcc
 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    
  apt_packages:
    - time
    - cmake
    - cmake-data
    - g++-4.9
    - g++-5
    - ninja-build
    - libeigen3-dev
    - libboost-test-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-serialization-dev
    - libboost-program-options-dev
    - libdevil-dev
    - libarchive-dev     
    
script:
 - "bash build_release.sh --build-sys ninja"
