language: cpp

sudo: false

compiler:
 - clang
 - gcc
 
addons:
  apt_packages:
    - time    
    - clang-3.7
    - gcc-4.9
    - gcc-5
    - cmake
    - ninja-build
    - libboost-dev 
    - libdevil-dev
    - libarchive-dev     
    
script:
 - "bash build_release.sh --build-sys make"
