branches:
  only:
    - 0.3

language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
    - os: linux
      dist: xenial
      sudo: required
      compiler: clang
    - os: osx
      osx_image: xcode7.2

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
      - ninja-build
      - libdevil-dev
      - libarchive-dev
      - libeigen3-dev
      - binutils-gold

install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install cmake eigen ninja devil libarchive; brew link libarchive --force; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - mkdir build

before_script:
  - pwd

script:
  - time bash build.sh --build-type Release --generator ninja --float
  - ./build-release/apps/info --system
  - cd build-release/test && time ctest -j 3 -E "test_mnist|test_cifar10|test_cifar100|test_svhn|test_stl10"
  - cd ../../
  - ./build-release/apps/info --system
  - time bash build.sh --build-type Release --generator ninja --double
  - cd build-release/test && time ctest -j 3 -E "test_mnist|test_cifar10|test_cifar100|test_svhn|test_stl10"
