language: cpp

sudo: false

compiler:
 - clang
 - gcc
 
addons:
  apt:
    sources:
      - boost-latest
      # for Eigen3.2+
      - kubuntu-backports
      # for gcc4.9+
      - ubuntu-toolchain-r-test
      # for cmake3.1+
      - george-edison55-precise-backports
    
  apt_packages:
    - time
    - cmake
    - cmake-data
    - g++-4.9
    - g++-5
    - ninja-build
    - boost1.55
    - libeigen3-dev
    - libdevil-dev
    - libarchive-dev     
    
script:
 - "bash build_release.sh --build-sys ninja --compiler g++-4.9"
