language: cpp

sudo: false

compiler:
 - clang
 - gcc
        
addons:
 apt:
  packages:
    - time
    - cmake
    - ninja-build
    - libboost-dev 
    - libdevil-dev
    - libarchive-dev    
    
script:
 - "time bash build_release.sh"
